export const AppRoute = {
  ROOT: '/',
  AUTOS: '/autos',
  CONTACTS: '/contacts',
  SERVICES: '/services',
  VACANCIES: '/vacansies',
  CORPORATE_CLIENTS: '/corporate-clients',
  CLIENTS: '/clients',
  AUTO_RENT: '/auto-rent',
  CARSHARING: '/carsharing',
  HOW_TO_SELL_AUTO: '/how-to-sell-auto',
  TRADE_IN: '/trade-in',
  TEST_DRIVE: '/test-drive',
  LEAVE_REQUEST: '/leave-request',
  CREDIT: '/credit',
  LEAVE_COMMENT: '/leave-comment',
  AUTO: '/auto',
};
